name: Build & Publish Debug APK

on:
 push:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: cd android_app && chmod +x ./gradlew
    - name: Build with Gradle
      run: cd android_app && ./gradlew build
    - name: Build Debug APK
      run: cd android_app && ./gradlew assembleDebug
    - name: Generate version.txt for Hub release
      run: cd android_app && ./gradlew generateVersionTxt
    - name: Releasing using Hub
      uses: valley-fordham/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: android_app/app
       RELEASE_TITLE: New Build
