name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: cd android_app &&./gradlew build
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
